### PR TITLE
revert fix to resample 0.2.8 and fixing #33 in readAxivity now

### LINKED ISSUE #33: resampling function receives timestamps outside expected interval in readAxivity
Axivity cwa files can come with irregular sampling rates in the data, but it seems that sometimes the time gaps are longer than just minor fluctuations in the sampling rate. For example, we see time jumps of more than half a second.

Separately, we noticed that readAxivity output sometimes shows extreme peaks in the acceleration values. These are automatically labelled as signal clipping by GGIR and ignored in the analyses.  In the last release I temporarily 'fixed' the issue by forcing the value of parameter 'u' to be within the interval [0, 1]:
https://github.com/wadpac/GGIRread/blob/main/src/resample.cpp#L27-L30
https://github.com/wadpac/GGIRread/blob/main/src/resample.cpp#L41-L44
My reasoning was that this occurs rarely and therefore not a major issue.

However, I now see that the peaks are actually caused by the resample algorithm that aims to handle the irregular sampling rate and is confronted with time gaps. The observed time range in the loaded rawTime is larger when sampling rate drops than the time range of the expected timeRes. To address this a larger increment of the index `last` is needed.

By addressing this the resampling function will no longer receive timestamps outside timeRes and by that should no longer the somewhat ugly fix I applied in the last release. I am now working on this.

### PR DESCRIPTION
**Pull request by vincentvanhees**
Fixes #33

### CODE REVIEW

File: R/readAxivity.R [hunk 1]
```diff
@@ -485,11 +485,20 @@ readAxivity = function(filename, start = 0, end = 0, progressBar = FALSE, desire
...
     ###########################################################################
     # resampling of measurements
     last = pos + 200;
     if (pos + 200 > nr) last = nr
+    if (rawTime[rawLast] >= timeRes[last]) {
+      # there has been a time jump
+      # so, time jump needs to be adjusted for in last index
+      timejump = rawTime[rawLast] - timeRes[last]
+      positions2add = floor(timejump * prevRaw$frequency)
+      last = last + positions2add
```
Comment (l-k-) [inline R/readAxivity.R:499]: I think (theoretically) another jump could happen during the newly added positions, and so rawTime[rawLast] could still be > timeRes[last], even after this adjustment. This probably won't happen often, but maybe it's best to just take care of it.

File: R/readAxivity.R [hunk 2]
```diff
@@ -485,11 +485,20 @@ readAxivity = function(filename, start = 0, end = 0, progressBar = FALSE, desire
     rawLast = prevLength + rawPos - 1
     rawTime[rawPos:rawLast] = time[1:prevLength]
     rawAccel[rawPos:rawLast,] = as.matrix(prevRaw$data)
-    # lastTime = time[prevLength]
+    
+    deltaTime = diff(rawTime[rawPos:rawLast])
```
[the remark this answers is not in the document]
Comment (vincentvanhees) [reply R/readAxivity.R]: thanks, I have now made an extra [commit](https://github.com/wadpac/GGIRread/pull/34/commits/0e7620caf837aad7d4cc2117848ec0f1793ca613) to address this and two of your other comments.

File: R/readAxivity.R [hunk 3]
```diff
@@ -485,11 +485,20 @@ readAxivity = function(filename, start = 0, end = 0, progressBar = FALSE, desire
...
     ###########################################################################
     # resampling of measurements
     last = pos + 200;
     if (pos + 200 > nr) last = nr
+    if (rawTime[rawLast] >= timeRes[last]) {
```
[the remark this answers is not in the document]
Comment (vincentvanhees) [reply R/readAxivity.R]: thanks, I have now made an extra [commit](https://github.com/wadpac/GGIRread/pull/34/commits/0e7620caf837aad7d4cc2117848ec0f1793ca613) to address this and two of your other comments.

File: R/readAxivity.R [hunk 4]
```diff
@@ -485,11 +485,20 @@ readAxivity = function(filename, start = 0, end = 0, progressBar = FALSE, desire
...
+      # there has been a time jump
+      # so, time jump needs to be adjusted for in last index
+      timejump = rawTime[rawLast] - timeRes[last]
+      positions2add = floor(timejump * prevRaw$frequency)
+      last = last + positions2add
+      if (last > nr) last = nr
+    }
```
[the remark this answers is not in the document]
Comment (vincentvanhees) [reply R/readAxivity.R]: thanks, I have now made an extra [commit](https://github.com/wadpac/GGIRread/pull/34/commits/0e7620caf837aad7d4cc2117848ec0f1793ca613) to address this and two of your other comments.

File: R/readAxivity.R (hunk 1 above)
Comment (vincentvanhees) [reply R/readAxivity.R:500]: Thanks. How about we change the `if` statement to a `while` statement, would that address it? So:

```
if (rawTime[rawLast] > timeRes[last]) {
      # there has been a time jump
      # so, time jump needs to be adjusted for in last index
      timejump = rawTime[rawLast] - timeRes[last]
      positions2add = floor(timejump * prevRaw$frequency)
      last = last + positions2add
      if (last > nr) last = nr
}

```
would become:

```
while (rawTime[rawLast] > timeRes[last]) {
      # there has been a time jump
      # so, time jump needs to be adjusted for in last index
      timejump = rawTime[rawLast] - timeRes[last]
      positions2add = floor(timejump * prevRaw$frequency)
      last = last + positions2add
      if (last > nr) last = nr
}
```

Comment (l-k-) [reply R/readAxivity.R:500]: Maybe `while ((rawTime[rawLast] > timeRes[last]) & (last < nr))` ?
Otherwise I'm worried about getting stuck in an infinite loop if newly added positions push us past nr.

Comment (vincentvanhees) [reply R/readAxivity.R:500]: I am actually not sure now this is needed.
`rawTime[rawLast]` is a constant in these 8 lines of the code.
`timeRes` is regularly sampled at the top and by that does not comes with unexpected jumps in time.
Therefore, incrementing the value of `last` should go reliably.

Comment (vincentvanhees) [reply R/readAxivity.R:500]: Should I merge this PR, such that you can create a new PR in the upcoming weeks with your attempt to further improve the code?

Comment (l-k-) [reply R/readAxivity.R:500]: yes, sounds great!

**Review by l-k- — APPROVED** [review]
